from typing import List, Literal, Optional
from pydantic import BaseModel, Field

# -------------------------------------------------------------------
# Option Framing
# -------------------------------------------------------------------
class OptionDraft(BaseModel):
    """Generated by the Architect to frame possible directions."""
    id: str = Field(..., description="Unique identifier for this option (e.g., 'opt_1')")
    title: str = Field(..., description="Short name for the option")
    summary: str
    benefits: List[str]
    trade_offs: List[str]
    complexity: Literal["low", "medium", "high"]
    operational_risk: Literal["low", "medium", "high"]
    implementation_effort: Literal["low", "medium", "high", "extreme"]
    alignment_with_vibe: str = Field(..., description="How well this preserves the core intent")

# -------------------------------------------------------------------
# Stress Test / Critique
# -------------------------------------------------------------------
class CritiqueFinding(BaseModel):
    severity: Literal["low", "medium", "high", "blocker"]
    challenged_assumption: str = Field(..., description="Which assumption is being invalidated")
    description: str
    mitigation: str

class CritiqueReport(BaseModel):
    """Generated by the Critic after stress testing an OptionDraft."""
    option_id: str
    findings: List[CritiqueFinding]
    implementation_hazards: List[str]
    dependency_risks: List[str]
    ambiguity_risks: List[str]
    recommendation_status: Literal["proceed", "pivot", "reject"]

# -------------------------------------------------------------------
# Core Artifacts
# -------------------------------------------------------------------
class ProjectSpec(BaseModel):
    """The canonical output of the Idea-to-Spec phase."""
    title: str
    core_intent: str = Field(..., description="The anchor to preserve the 'vibe'")
    problem_statement: str
    target_users: List[str]
    user_value: str
    success_criteria: List[str]
    assumptions: List[str]
    decisions: List[str]
    constraints: List[str]
    non_negotiables: List[str]
    non_goals: List[str]
    options_considered: List[str] = Field(..., description="Summary of rejected options and why")
    chosen_approach: str
    functional_requirements: List[str]
    non_functional_requirements: List[str]
    data_model_outline: List[str]
    interfaces: List[str]
    in_scope: List[str]
    out_of_scope: List[str]
    maybe_later: List[str]
    risks: List[str]
    open_questions: List[str]
    acceptance_criteria: List[str]

class ImplementationSpec(BaseModel):
    """The canonical output of the Spec-to-Impl phase."""
    implementation_goal: str
    architecture_summary: str
    strategies_considered: List[str]
    chosen_strategy: str
    module_boundaries: List[str]
    integration_points: List[str]
    error_handling_strategy: str
    test_strategy: str
    technical_debt_register: List[str]
    delivery_sequence: List[str]
    tie_breaker_heuristics: List[str]
