from typing import Literal

from pydantic import BaseModel, Field


# -------------------------------------------------------------------
# Option Framing
# -------------------------------------------------------------------
class OptionDraft(BaseModel):
    """Generated by the Architect to frame possible directions."""

    id: str = Field(..., description="Unique identifier for this option (e.g., 'opt_1')")
    title: str = Field(..., description="Short name for the option")
    summary: str
    benefits: list[str]
    trade_offs: list[str]
    complexity: Literal["low", "medium", "high"]
    operational_risk: Literal["low", "medium", "high"]
    implementation_effort: Literal["low", "medium", "high", "extreme"]
    alignment_with_vibe: str = Field(..., description="How well this preserves the core intent")


# -------------------------------------------------------------------
# Stress Test / Critique
# -------------------------------------------------------------------
class CritiqueFinding(BaseModel):
    severity: Literal["low", "medium", "high", "blocker"]
    challenged_assumption: str = Field(..., description="Which assumption is being invalidated")
    description: str
    mitigation: str


class CritiqueReport(BaseModel):
    """Generated by the Critic after stress testing an OptionDraft."""

    option_id: str
    findings: list[CritiqueFinding]
    implementation_hazards: list[str]
    dependency_risks: list[str]
    ambiguity_risks: list[str]
    recommendation_status: Literal["proceed", "pivot", "reject"]


# -------------------------------------------------------------------
# Core Artifacts
# -------------------------------------------------------------------
class ProjectSpec(BaseModel):
    """The canonical output of the Idea-to-Spec phase."""

    title: str
    core_intent: str = Field(..., description="The anchor to preserve the 'vibe'")
    problem_statement: str
    target_users: list[str]
    user_value: str
    success_criteria: list[str]
    assumptions: list[str]
    decisions: list[str]
    constraints: list[str]
    non_negotiables: list[str]
    non_goals: list[str]
    options_considered: list[str] = Field(..., description="Summary of rejected options and why")
    chosen_approach: str
    functional_requirements: list[str]
    non_functional_requirements: list[str]
    data_model_outline: list[str]
    interfaces: list[str]
    in_scope: list[str]
    out_of_scope: list[str]
    maybe_later: list[str]
    risks: list[str]
    open_questions: list[str]
    acceptance_criteria: list[str]


class ImplementationSpec(BaseModel):
    """The canonical output of the Spec-to-Impl phase."""

    implementation_goal: str
    architecture_summary: str
    strategies_considered: list[str]
    chosen_strategy: str
    module_boundaries: list[str]
    integration_points: list[str]
    error_handling_strategy: str
    test_strategy: str
    technical_debt_register: list[str]
    delivery_sequence: list[str]
    tie_breaker_heuristics: list[str]
