import logging
from typing import List, Literal

from pydantic import BaseModel, Field
from sqlmodel import Session

from core.logging_utils import get_logger, log_event
from core.models import ArtifactType
from core.schemas import CritiqueReport, ImplementationSpec, OptionDraft, ProjectSpec
from core.skills import build_stage_system_prompt, get_stage_skill_snapshot
from core.state import ChorusState
from db.database import engine
from db.operations import save_artifact
from llm.routing import generate_structured_output

# -------------------------------------------------------------------
# Intermediate Pydantic Models for internal node logic
# -------------------------------------------------------------------
logger = get_logger(__name__)


class MaturityClassification(BaseModel):
    maturity: Literal["raw", "partial", "mature"] = Field(..., description="Strict classification of input maturity.")
    summary: str

class ExplorationDraft(BaseModel):
    problem_statement: str
    target_users: List[str]
    constraints: List[str]
    success_criteria: List[str]

class OptionsList(BaseModel):
    simplest_viable: OptionDraft = Field(..., description="The absolute simplest viable approach.")
    scalable: OptionDraft = Field(..., description="A robust, scalable approach.")
    minimal_cost: OptionDraft = Field(..., description="An MVP approach optimizing for lowest immediate cost.")

class CritiquesList(BaseModel):
    reports: List[CritiqueReport]


def _persist_prompt_contract(run_id: int | None, stage: str, system_prompt: str) -> None:
    if not run_id:
        return

    payload = {
        **get_stage_skill_snapshot(stage),  # type: ignore[arg-type]
        "system_prompt": system_prompt,
    }
    with Session(engine) as session:
        save_artifact(session, run_id, ArtifactType.prompt_contract, payload)

# -------------------------------------------------------------------
# Node Implementations
# -------------------------------------------------------------------
def intake_node(state: ChorusState):
    """Explorer: Classifies input maturity."""
    log_event(logger, logging.INFO, "node_started", run_id=state.get("run_id"), stage="intake")
    system_prompt = build_stage_system_prompt(
        "intake",
        "You classify product specs. Return maturity as 'raw', 'partial', or 'mature'.",
    )
    _persist_prompt_contract(state.get("run_id"), "intake", system_prompt)
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Classify this input:\n\n{state['raw_input']}"}
    ]
    
    classification = generate_structured_output(MaturityClassification, messages, profile="extraction")
    return {"current_stage": "intake", "input_maturity": classification.maturity}


def exploration_node(state: ChorusState):
    """Explorer: Expands raw idea into constraints and problem statements."""
    log_event(logger, logging.INFO, "node_started", run_id=state.get("run_id"), stage="exploration")
    system_prompt = build_stage_system_prompt(
        "exploration",
        "Extract the core problem, target users, and implicit constraints from this raw idea. Do not solve the problem yet.",
    )
    _persist_prompt_contract(state.get("run_id"), "exploration", system_prompt)
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Idea:\n{state['raw_input']}"}
    ]
    
    draft = generate_structured_output(ExplorationDraft, messages, profile="synthesis")
    
    # Save the exploration draft separately to avoid mutating raw_input
    return {"current_stage": "exploration", "exploration_draft": draft.model_dump()}


def framing_node(state: ChorusState):
    """Architect: Generates multiple option drafts."""
    log_event(logger, logging.INFO, "node_started", run_id=state.get("run_id"), stage="framing")
    
    exploration_context = ""
    if state.get("exploration_draft"):
        exploration_context = f"\n\nExploration Findings:\n{state['exploration_draft']}"
    system_prompt = build_stage_system_prompt(
        "framing",
        "Generate exactly 3 distinct options: simplest_viable, scalable, and minimal_cost.",
    )
    _persist_prompt_contract(state.get("run_id"), "framing", system_prompt)
        
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Raw Context:\n{state['raw_input']}{exploration_context}"}
    ]
    
    result = generate_structured_output(OptionsList, messages, profile="synthesis")
    
    # Flatten strictly requested fields into the list expected by the state
    options_list = [result.simplest_viable, result.scalable, result.minimal_cost]
    return {"current_stage": "framing", "options_drafts": options_list}


def critic_node(state: ChorusState):
    """Critic: Stress tests the options generated by the Architect."""
    log_event(logger, logging.INFO, "node_started", run_id=state.get("run_id"), stage="critic")
    
    options_json = "\n".join([opt.model_dump_json() for opt in state.get("options_drafts", [])])
    system_prompt = build_stage_system_prompt(
        "critic",
        "Critique the provided implementation options. Be ruthless about complexity, assumptions, and edge cases. Status must be 'proceed', 'pivot', or 'reject'.",
    )
    _persist_prompt_contract(state.get("run_id"), "critic", system_prompt)
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Options to critique:\n{options_json}"}
    ]
    
    result = generate_structured_output(CritiquesList, messages, profile="critic")
    
    reports = result.reports
    update = {"current_stage": "critic", "critique_reports": reports}
    
    if reports and all(r.recommendation_status == "reject" for r in reports):
        update["loop_count"] = state.get("loop_count", 0) + 1
        
    return update


def mediator_node(state: ChorusState):
    """Scope Guardian / Spec Writer: Synthesizes final ProjectSpec."""
    log_event(logger, logging.INFO, "node_started", run_id=state.get("run_id"), stage="mediator")
    
    options_json = "\n".join([opt.model_dump_json() for opt in state.get("options_drafts", [])])
    critiques_json = "\n".join([r.model_dump_json() for r in state.get("critique_reports", [])])
    exploration_context = state.get("exploration_draft", {})
    system_prompt = build_stage_system_prompt(
        "mediator",
        "Synthesize the final Project Spec. Choose the best approach based on the Architect's options and the Critic's reports. Enforce MVP boundaries.",
    )
    _persist_prompt_contract(state.get("run_id"), "mediator", system_prompt)
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Original Idea: {state['raw_input']}\nExploration: {exploration_context}\nOptions:\n{options_json}\nCritiques:\n{critiques_json}"}
    ]
    
    final_spec = generate_structured_output(ProjectSpec, messages, profile="synthesis")
    
    # Persist artifact
    if state.get("run_id"):
        with Session(engine) as session:
            save_artifact(session, state["run_id"], ArtifactType.project_spec, final_spec)
            
    return {"current_stage": "mediator", "project_spec": final_spec}

def implementation_debate_node(state: ChorusState):
    """Implementation Architect: Debates architecture and produces ImplementationSpec."""
    log_event(logger, logging.INFO, "node_started", run_id=state.get("run_id"), stage="implementation_debate")
    
    project_spec_json = state.get("project_spec").model_dump_json() if state.get("project_spec") else state.get("raw_input")
    system_prompt = build_stage_system_prompt(
        "implementation_debate",
        "Translate the approved ProjectSpec into an ImplementationSpec. Detail architecture, boundaries, and delivery sequence.",
    )
    _persist_prompt_contract(state.get("run_id"), "implementation_debate", system_prompt)
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Project Spec:\n{project_spec_json}"}
    ]
    
    impl_spec = generate_structured_output(ImplementationSpec, messages, profile="synthesis")
    
    # Persist artifact
    if state.get("run_id"):
        with Session(engine) as session:
            save_artifact(session, state["run_id"], ArtifactType.implementation_spec, impl_spec)
            
    return {"current_stage": "implementation_debate", "implementation_spec": impl_spec}
