import logging
from collections.abc import Callable
from dataclasses import dataclass
from typing import Literal, TypedDict, TypeVar

from langgraph.types import Command, interrupt

from core.logging_utils import get_logger, log_event
from core.models import ArtifactType
from core.node_runtime import DefaultNodeRuntime, NodeRuntime
from core.prompt_builders import (
    PromptPackage,
    build_critic_prompt,
    build_exploration_prompt,
    build_framing_prompt,
    build_implementation_prompt,
    build_intake_prompt,
    build_mediator_prompt,
)
from core.schemas import CritiqueReport, ImplementationSpec, ProjectSpec
from core.skills import get_stage_skill_snapshot
from core.state import (
    ChorusState,
    CritiquesList,
    ExplorationDraft,
    MaturityClassification,
    OptionsBundle,
)

logger = get_logger(__name__)
GeneratedModelT = TypeVar("GeneratedModelT")

# Backward-compatible alias for existing imports/tests.
OptionsList = OptionsBundle


class IntakeNodeUpdate(TypedDict):
    current_stage: str
    input_maturity: str


class ExplorationNodeUpdate(TypedDict):
    current_stage: str
    exploration_draft: ExplorationDraft


class FramingNodeUpdate(TypedDict):
    current_stage: str
    options_bundle: OptionsBundle


class CriticNodeUpdate(TypedDict, total=False):
    current_stage: str
    critique_reports: list[CritiqueReport]
    loop_count: int


CriticNextNode = Literal["exploration", "mediator"]


class MediatorNodeUpdate(TypedDict):
    current_stage: str
    project_spec: ProjectSpec


class HumanReviewNodeUpdate(TypedDict):
    current_stage: str
    human_feedback: str | dict[str, object] | None


class ImplementationNodeUpdate(TypedDict):
    current_stage: str
    implementation_spec: ImplementationSpec


@dataclass(frozen=True)
class NodeHandlers:
    intake: Callable[[ChorusState], IntakeNodeUpdate]
    exploration: Callable[[ChorusState], ExplorationNodeUpdate]
    framing: Callable[[ChorusState], FramingNodeUpdate]
    critic: Callable[[ChorusState], Command[CriticNextNode]]
    mediator: Callable[[ChorusState], MediatorNodeUpdate]
    human_review: Callable[[ChorusState], HumanReviewNodeUpdate]
    implementation_debate: Callable[[ChorusState], ImplementationNodeUpdate]


def _persist_prompt_contract(runtime: NodeRuntime, run_id: int | None, stage: str, system_prompt: str) -> None:
    if not run_id:
        return

    payload = {
        **get_stage_skill_snapshot(stage),  # type: ignore[arg-type]
        "system_prompt": system_prompt,
    }
    runtime.persist_artifact(run_id, ArtifactType.prompt_contract, payload)


def _run_stage_generation[GeneratedModelT](
    *,
    state: ChorusState,
    runtime: NodeRuntime,
    stage: str,
    prompt: PromptPackage,
    response_model: type[GeneratedModelT],
) -> GeneratedModelT:
    log_event(logger, logging.INFO, "node_started", run_id=state.get("run_id"), stage=stage)
    _persist_prompt_contract(runtime, state.get("run_id"), prompt["stage"], prompt["system_prompt"])
    return runtime.generate(response_model, prompt["messages"], profile=prompt["profile"])  # type: ignore[type-var]


def intake_node_with_runtime(state: ChorusState, runtime: NodeRuntime) -> IntakeNodeUpdate:
    """Explorer: Classifies input maturity."""
    prompt = build_intake_prompt(state["raw_input"])
    classification = _run_stage_generation(
        state=state,
        runtime=runtime,
        stage="intake",
        prompt=prompt,
        response_model=MaturityClassification,
    )
    return {"current_stage": "intake", "input_maturity": classification.maturity}


def exploration_node_with_runtime(state: ChorusState, runtime: NodeRuntime) -> ExplorationNodeUpdate:
    """Explorer: Expands raw idea into constraints and problem statements."""
    prompt = build_exploration_prompt(state["raw_input"])
    draft = _run_stage_generation(
        state=state,
        runtime=runtime,
        stage="exploration",
        prompt=prompt,
        response_model=ExplorationDraft,
    )
    return {"current_stage": "exploration", "exploration_draft": draft}


def framing_node_with_runtime(state: ChorusState, runtime: NodeRuntime) -> FramingNodeUpdate:
    """Architect: Generates multiple option drafts."""
    prompt = build_framing_prompt(state["raw_input"], state.get("exploration_draft"))
    result = _run_stage_generation(
        state=state,
        runtime=runtime,
        stage="framing",
        prompt=prompt,
        response_model=OptionsBundle,
    )
    return {"current_stage": "framing", "options_bundle": result}


def critic_node_with_runtime(state: ChorusState, runtime: NodeRuntime) -> Command[CriticNextNode]:
    """Critic: Stress tests the options generated by the Architect."""
    prompt = build_critic_prompt(state.get("options_bundle"))
    result = _run_stage_generation(
        state=state,
        runtime=runtime,
        stage="critic",
        prompt=prompt,
        response_model=CritiquesList,
    )

    reports = result.reports
    update: CriticNodeUpdate = {"current_stage": "critic", "critique_reports": reports}

    if reports and all(r.recommendation_status == "reject" for r in reports):
        update["loop_count"] = state.get("loop_count", 0) + 1

    goto: CriticNextNode = "mediator"
    if not reports:
        goto = "mediator"
    elif all(r.recommendation_status == "reject" for r in reports):
        goto = "mediator" if update.get("loop_count", state.get("loop_count", 0)) >= 3 else "exploration"

    return Command(update=update, goto=goto)


def mediator_node_with_runtime(state: ChorusState, runtime: NodeRuntime) -> MediatorNodeUpdate:
    """Scope Guardian / Spec Writer: Synthesizes final ProjectSpec."""
    prompt = build_mediator_prompt(
        state["raw_input"],
        state.get("exploration_draft"),
        state.get("options_bundle"),
        state.get("critique_reports", []),
    )
    final_spec = _run_stage_generation(
        state=state,
        runtime=runtime,
        stage="mediator",
        prompt=prompt,
        response_model=ProjectSpec,
    )

    if state.get("run_id"):
        runtime.persist_artifact(state["run_id"], ArtifactType.project_spec, final_spec)

    return {"current_stage": "mediator", "project_spec": final_spec}


def human_review_node(state: ChorusState) -> HumanReviewNodeUpdate:
    log_event(logger, logging.INFO, "node_started", run_id=state.get("run_id"), stage="human_review")
    project_spec = state.get("project_spec")
    feedback = interrupt(
        {
            "artifact_type": "project_spec",
            "current_stage": "human_review",
            "project_spec": project_spec.model_dump() if project_spec else None,
            "message": "Review the generated project spec before continuing.",
        }
    )
    return {"current_stage": "human_review", "human_feedback": feedback}


def implementation_debate_node_with_runtime(state: ChorusState, runtime: NodeRuntime) -> ImplementationNodeUpdate:
    """Implementation Architect: Debates architecture and produces ImplementationSpec."""
    prompt = build_implementation_prompt(state["raw_input"], state.get("project_spec"))
    impl_spec = _run_stage_generation(
        state=state,
        runtime=runtime,
        stage="implementation_debate",
        prompt=prompt,
        response_model=ImplementationSpec,
    )

    if state.get("run_id"):
        runtime.persist_artifact(state["run_id"], ArtifactType.implementation_spec, impl_spec)

    return {"current_stage": "implementation_debate", "implementation_spec": impl_spec}


def build_node_handlers(runtime: NodeRuntime) -> NodeHandlers:
    return NodeHandlers(
        intake=lambda state: intake_node_with_runtime(state, runtime),
        exploration=lambda state: exploration_node_with_runtime(state, runtime),
        framing=lambda state: framing_node_with_runtime(state, runtime),
        critic=lambda state: critic_node_with_runtime(state, runtime),
        mediator=lambda state: mediator_node_with_runtime(state, runtime),
        human_review=human_review_node,
        implementation_debate=lambda state: implementation_debate_node_with_runtime(state, runtime),
    )


_DEFAULT_NODE_HANDLERS = build_node_handlers(DefaultNodeRuntime())


def intake_node(state: ChorusState) -> IntakeNodeUpdate:
    return _DEFAULT_NODE_HANDLERS.intake(state)


def exploration_node(state: ChorusState) -> ExplorationNodeUpdate:
    return _DEFAULT_NODE_HANDLERS.exploration(state)


def framing_node(state: ChorusState) -> FramingNodeUpdate:
    return _DEFAULT_NODE_HANDLERS.framing(state)


def critic_node(state: ChorusState) -> Command[CriticNextNode]:
    return _DEFAULT_NODE_HANDLERS.critic(state)


def mediator_node(state: ChorusState) -> MediatorNodeUpdate:
    return _DEFAULT_NODE_HANDLERS.mediator(state)


def human_review_node_default(state: ChorusState) -> HumanReviewNodeUpdate:
    return _DEFAULT_NODE_HANDLERS.human_review(state)


def implementation_debate_node(state: ChorusState) -> ImplementationNodeUpdate:
    return _DEFAULT_NODE_HANDLERS.implementation_debate(state)
